export const FETCH_UPLOAD_IMG_ROOM_SUCCESS = '@@room/FETCH_UPLOAD_IMG_ROOM_SUCCESS';
export const FETCH_UPLOAD_IMG_ROOM_REQUEST = '@@room/FETCH_UPLOAD_IMG_ROOM_REQUEST';
export const FETCH_UPLOAD_IMG_ROOM_FAIL = '@@room/FETCH_UPLOAD_IMG_ROOM_FAIL';
