export const FETCH_UPLOAD_IMG_VITRI_SUCCESS = '@@user/FETCH_UPLOAD_IMG_VITRI_SUCCESS';
export const FETCH_UPLOAD_IMG_VITRI_REQUEST = '@@user/FETCH_UPLOAD_IMG_VITRI_REQUEST';
export const FETCH_UPLOAD_IMG_VITRI_FAIL = '@@user/FETCH_UPLOAD_IMG_VITRI_FAIL';
